#!/bin/bash
# nfs-remount - if some nfs mounts are missing, retry
d=$(df -T | grep '\<nfs\>' | wc -l)
f=$(cat /etc/fstab | grep -v '^#' | grep '\<nfs\>' | wc -l)
if [ $d -ne $f ]; then
  mount -a -t nfs
fi
