#!/bin/bash
# v3 smartctl disk check
# v4 set RAID in .conf
# v5 adjust use of smartctl
Name=$( basename $0 )
if [[ -r $0.conf ]]; then . $0.conf; else echo no $0.conf; exit 1; fi

# smartctl -A -d sat+megaraid,12 /dev/sda
# smartctl -A -d 3ware,1 /dev/twa0 # 9650 
# smartctl -A -d 3ware,1 /dev/twl0 # 9750 

# reporting
# 5 Reallocated_Sector_Ct   0x0033   001   001   005    Pre-fail  Always   FAILING_NOW 1990
awkS='
/^  5 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
/^ 10 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
/^194 /{if ($10 > 36) printf " %d %s %s ", $10, $9, $2 }
/^197 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
/^198 /{if ($10 > 0) printf " %d %s %s ", $10, $9, $2 }
/^  9 /{x=$10/24/365; if (x > 4) printf "(%1.1f years) ", x }
'
#awkS='/^  5 /{printf "%d = %s ", $10, $2 }'

# quickie
if [[ -n "$1" ]]; then
  echo "== $1"
  smartctl -d sat -A $1 
  exit
fi
  

# figure out disks
# smartctl --scan for AT disks, dmesg scsi# for raid controllers
# could use lsblk

# SATA or PATA
Sata=$( smartctl --scan-open | awk '/ sat /{print $1}')

# hello
echo == smart: looking for sector errs on $( hostname )
if [[ -n "$Sata" ]]; then echo SATA $Sata; fi

## non-raid
for i in $Sata; do
  out=$( smartctl -d sat -A $i | awk "$awkS" )
  if [[ -n $out ]]; then
    echo "disk $i SATA $out"
  fi
done

## raid
if [[ -n "$Rtype" ]]; then echo RAID $Rtype $Rdev; fi
for (( j=0; j<32; j++ )); do
  out=$( smartctl -d $Rtype,$j -A $Rdev | awk "$awkS" )
  if [[ -n "$out" ]]; then
    echo "disk $j $out"
  fi
done

## raid2
if [[ -n "$Rtype2" ]]; then echo RAID $Rtype2 $Rdev2; fi
for (( j=0; j<32; j++ )); do
  out=$( smartctl -d $Rtype2,$j -A $Rdev2 | awk "$awkS" )
  if [[ -n "$out" ]]; then
    echo "disk $j $out"
  fi
done

