#!/bin/sh
tmp=/tmp/update_message
yum -y --exclude=samba* update &> $tmp
cat $tmp | mailx -s yum-update root 
if ! yum check-updates; then
  grep samba $tmp | mailx -s "$(hostname -s) urgent : yum samba updates" root
fi
rpm -qa --last > /root/rpm-qa--last
