#!/bin/bash
# originally in v3 smartctl disk check

# LSI sat+megaraid,12 /dev/sda
# 3ware 3ware,1 and 9750 /dev/twl0, 9650 /dev/twa0
# RAID controllers
# drivers find cards during boot
Raid=$( 
cat /var/log/dmesg | egrep '^scsi[0-9]' | 
  while read scsi sep line; do
    case "$line" in
      (LSI*MegaRAID*) 
        # LSI so find an associated sd line
        echo 'sat+megaraid'
        # strip 'scsi' off front leaving digit
        sd=${scsi#scsi}
        disk=$( cat /var/log/dmesg | egrep "^sd $sd" | cut -f3 -d' ' )
        # strip off []
        echo "/dev/${disk:1:3}"
        ;;
      (3w-sas*) 
        # 9750
        echo 3ware
        echo /dev/twl$((x97++))
        ;;
      (3ware*) 
        # 9690 9650 9550
        echo 3ware
        echo /dev/twa$((x9X++))
        ;;
    esac
  done )

if [[ -n "$Raid" ]]; then 
  echo $Raid
  exit 0
else
  exit 1
fi

